"""Firmware Board Support Package (BSP) Generator.

This module traverses the compiled hardware graph to automatically 
generate C/C++ header files mapping MCU GPIOs to peripheral interfaces.
"""

import datetime
from pathlib import Path

from openhac.core.board import Board
import openhac.core.circuit


def generate_c_header(board: Board, output_path: str | Path) -> None:
    """Generate a C/C++ board_config.h header file from the compiled netlist.
    
    Args:
        board: The compiled Board object.
        output_path: Path to write the header file.
    """
    circuit = openhac.core.circuit.default_circuit
    nets = getattr(circuit, "nets", [])
    
    macros = []
    
    # Simple heuristic to identify MCU vs Peripheral pins:
    # A pin is an MCU GPIO if its name starts with P (e.g., PA4, PB12), GPIO, or IO.
    for net in nets:
        net_name = getattr(net, "name", "Unnamed")
        if net_name.upper() in ("GND", "VCC", "VDD", "NC"):
            continue
            
        pins = getattr(net, "pins", [])
        if len(pins) < 2:
            continue
            
        mcu_pins = []
        peripheral_pins = []
        
        for pin in pins:
            pin_name = str(getattr(pin, "name", "")).upper()
            refdes = getattr(pin.part, "refdes", "?") if hasattr(pin, "part") else "?"
            
            is_mcu = pin_name.startswith("P") and len(pin_name) >= 3 and pin_name[1].isalpha() and pin_name[2].isdigit() # e.g. PA4
            is_mcu = is_mcu or pin_name.startswith("GPIO") or pin_name.startswith("IO")
            
            if is_mcu:
                mcu_pins.append((refdes, pin_name))
            else:
                peripheral_pins.append((refdes, pin_name))
                
        # If we have exactly one MCU pin and at least one peripheral, we can generate a mapping!
        if len(mcu_pins) == 1 and len(peripheral_pins) >= 1:
            mcu_ref, mcu_pin = mcu_pins[0]
            for peri_ref, peri_pin in peripheral_pins:
                # e.g., #define S1_DATA_PIN GPIO1
                macro_name = f"{peri_ref}_{peri_pin}_PIN".replace("-", "_").upper()
                macros.append(f"#define {macro_name:<20} {mcu_pin}  // Connected via Net: {net_name}")

    out_path = Path(output_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(out_path, "w") as f:
        f.write("/**\n")
        f.write(" * Automatically generated Board Support Package (BSP) Configuration\n")
        f.write(f" * Generated by OpenHaC on {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(" * \n")
        f.write(" * Do not edit manually. Changes will be overwritten during hardware compilation.\n")
        f.write(" */\n\n")
        
        f.write("#pragma once\n\n")
        
        if not macros:
            f.write("// No MCU-to-Peripheral connections detected in the hardware graph.\n")
        else:
            for macro in sorted(macros):
                f.write(f"{macro}\n")
                
        f.write("\n// EOF\n")
