"""Best-effort compile post-report for dev/handoff debugging.

This report is not a quality gate; it exists to summarize common "why did this happen?"
issues (implicit pins, pad mismatches) into a single artifact.
"""

from __future__ import annotations

import json
from pathlib import Path


def _safe_sort_key(d: dict, *keys: str) -> tuple:
    out: list[str] = []
    for k in keys:
        try:
            out.append(str(d.get(k, "") or ""))
        except Exception:
            out.append("")
    return tuple(out)


def write_compile_post_report(state) -> str | None:
    base = Path(state.output_dir).resolve() if state.output_dir is not None else Path.cwd().resolve()
    out = base / f"{state.project_name}.openhac-compile-post-report.md"
    out_json = base / f"{state.project_name}.openhac-needs-enrichment.json"
    out_pinpad = base / f"{state.project_name}.openhac-pin-pad-report.json"

    pin_pad_records: list[dict] = []
    try:
        from openhac.compiler.pcb_placement import pin_pad_mismatch_records

        if not getattr(state, "skip_layout", False):
            pin_pad_records = pin_pad_mismatch_records(state.board)
    except Exception:
        pin_pad_records = []
    try:
        out_pinpad.write_text(json.dumps(pin_pad_records, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    except Exception:
        pass

    try:
        from openhac.core import base as core_base

        implicit_events = list(getattr(core_base, "_IMPLICIT_PIN_EVENTS", []) or [])
    except Exception:
        implicit_events = []

    try:
        from openhac.compiler import pcb_placement

        pad_events = list(getattr(pcb_placement, "_PAD_MISMATCH_EVENTS", []) or [])
    except Exception:
        pad_events = []

    implicit_events = sorted(implicit_events, key=lambda d: _safe_sort_key(d, "generic_name", "refdes", "pin_name"))
    pad_events = sorted(pad_events, key=lambda d: _safe_sort_key(d, "refdes", "footprint", "pin_num", "net"))

    # Machine-readable to-do list.
    needs: dict[str, dict] = {}
    for ev in implicit_events:
        gn = str(ev.get("generic_name") or "").strip() or "?"
        needs.setdefault(gn, {"generic_name": gn, "implicit_pins": set(), "pad_mismatches": 0})
        try:
            needs[gn]["implicit_pins"].add(str(ev.get("pin_name") or ""))
        except Exception:
            pass
    for ev in pad_events:
        # Pad mismatches are recorded by refdes; best-effort map back to generic name via implicit table.
        # If unknown, bucket under '?'.
        gn = "?"
        needs.setdefault(gn, {"generic_name": gn, "implicit_pins": set(), "pad_mismatches": 0})
        try:
            needs[gn]["pad_mismatches"] += 1
        except Exception:
            pass

    try:
        payload = []
        for gn, rec in sorted(needs.items(), key=lambda kv: kv[0]):
            pins = sorted({p for p in (rec.get("implicit_pins") or set()) if p})
            payload.append(
                {
                    "generic_name": gn,
                    "implicit_pin_names": pins,
                    "implicit_pin_count": len(pins),
                    "pad_mismatch_count": int(rec.get("pad_mismatches") or 0),
                }
            )
        out_json.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    except Exception:
        pass

    lines: list[str] = []
    lines.append(f"# OpenHaC compile post-report: `{state.project_name}`")
    lines.append("")
    lines.append("This file is generated by the compiler as a **best-effort diagnostic summary**.")
    lines.append("")

    try:
        lines.append("## Inputs")
        lines.append(f"- **compile_goal**: `{getattr(state, 'compile_goal', '')}`")
        lines.append(f"- **bbox_padding_mm**: `{float(getattr(state, 'bbox_padding_mm', 0.5) or 0.0):.3f}`")
        try:
            em = dict(getattr(state, "enrich_metrics", {}) or {})
            lines.append(
                f"- **enrichment**: attempted `{em.get('attempted', 0)}`, updated `{em.get('updated', 0)}`, "
                f"failed `{em.get('failed', 0)}`, network `{bool(em.get('network', False))}`"
            )
        except Exception:
            pass
        if getattr(state, "source_script_path", None):
            lines.append(f"- **source_script_path**: `{state.source_script_path}`")
        lines.append("")
    except Exception:
        pass

    lines.append("## Implicit pin creations")
    lines.append(
        f"- **count**: `{len(implicit_events)}` (these come from named-pin access when DB pinout is missing)"
    )
    if implicit_events:
        lines.append("")
        lines.append("Top entries:")
        for ev in implicit_events[:50]:
            g = ev.get("generic_name", "?")
            r = ev.get("refdes", "?")
            p = ev.get("pin_name", "?")
            lines.append(f"- `{r}` `{g}`: `{p}`")
    else:
        lines.append("- (none captured)")
    lines.append("")
    lines.append("## Pad / footprint mismatches (net not attached)")
    lines.append(
        f"- **preflight records** (pin keys vs `.kicad_mod` pads): `{len(pin_pad_records)}` "
        f"— see `{out_pinpad.name}` (fields: refdes, generic_name, footprint, pin_num/name, net, footprint_pads_sample)."
    )
    lines.append(f"- **placement events captured**: `{len(pad_events)}`")
    if pad_events:
        lines.append("")
        lines.append("Top entries:")
        for ev in pad_events[:80]:
            r = ev.get("refdes", "?")
            fp = ev.get("footprint", "?")
            pn = ev.get("pin_num", "?")
            name = ev.get("pin_name", "")
            net = ev.get("net", "?")
            extra = f" ({name})" if name else ""
            lines.append(f"- `{r}` `{fp}`: pin `{pn}`{extra} net `{net}`")
    else:
        lines.append("- (none captured)")
    lines.append("")
    lines.append("## Needs enrichment (machine-readable)")
    lines.append(f"- JSON: `{out_json.name}`")
    lines.append("")
    lines.append("## Suggested next step (seed template)")
    lines.append(
        "If a part is repeatedly showing up above, add a `pinout` list (and optionally `symbol_data`) via:"
    )
    lines.append("")
    lines.append("```bash")
    lines.append("python3 -m openhac.database.sync_jlc --seed-file your_parts.json")
    lines.append("```")
    lines.append("")
    lines.append("Example seed snippet:")
    lines.append("")
    lines.append("```json")
    lines.append("{")
    lines.append('  "generic_name": "YOUR_PART_GENERIC_NAME",')
    lines.append('  "pinout": [')
    lines.append('    {"num": "1", "name": "VIN", "type": "power_in"},')
    lines.append('    {"num": "2", "name": "GND", "type": "power_in"}')
    lines.append("  ]")
    lines.append("}")
    lines.append("```")
    lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    return str(out)

